### ISSUE TITLE
跨服数据存在问题

### ISSUE THREAD

**Issue by NnnBbon** [liaojinmin/GeekRewardPlus#2]
mysql版本5.7.24
服务器核心：catserver 1.12.2

问题如下：
1.在数据库设置无问题且正常链接的情况下各个子服同步时间不统一（有的同步，有的则是重新开始同步？）
2.在领取在线奖励时，数据库会正常记录，但跨服后会将数据重新写入到数据库（像是覆盖）玩家可用此特性在所有子服领取多个在线奖励
![031741p6o200wa777bpowb](https://user-images.githubusercontent.com/110595024/211920837-3b7d4a4a-f375-4b9c-acf6-cb7c75418bcb.png)

**Comment by NnnBbon** [comment]
如上图，玩家可以领取多个30分钟礼包

**Comment by NnnBbon** [comment]
![图片](https://user-images.githubusercontent.com/110595024/211923501-1d269cbf-c64c-41c4-ac30-5f7a623fc2e7.png)

**Comment by liaojinmin** [comment]
预计月底发布重构版本，现在的代码太烂了。
