### ISSUE TITLE
排序乱序，且无法翻页，还会有重复的出现,后台无报错

### ISSUE THREAD

**Issue by Xnidada** [liaojinmin/GeekRewardPlus#5]
![image](https://github.com/liaojinmin/GeekRewardPlus/assets/99242646/a75d1026-0eb7-4c94-9036-ed48dd8948f6)
![image](https://github.com/liaojinmin/GeekRewardPlus/assets/99242646/758bbbbb-78f2-49f8-9a5a-a3a4c8dc70c8)
![image](https://github.com/liaojinmin/GeekRewardPlus/assets/99242646/798d2dac-33bb-40c1-acf6-985be0c963af)
![image](https://github.com/liaojinmin/GeekRewardPlus/assets/99242646/9c476127-fba3-4ddb-96bf-5b4286042de8)

**Comment by Xnidada** [comment]
1.12.2 catserver端

**Comment by liaojinmin** [comment]
将复现配置贴出

**Comment by liaojinmin** [comment]
已更新排序方法
